server:
  port: 8086

spring:
  application:
    name: review-service
  datasource:
    url: ${REVIEW_DB_URL:jdbc:postgresql://localhost:5432/review_db}
    username: ${REVIEW_DB_USERNAME:postgres}
    password: ${REVIEW_DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ${JWT_SECRET:default_secret}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
